
#
# Table structure generated by FORMgen, http://www.formfields.com
#

DROP TABLE IF EXISTS `contact`;

CREATE TABLE `contact` (
	`__id` int(10) unsigned NOT NULL auto_increment,
	Name VARCHAR(30),
	Email VARCHAR(50),
	Location VARCHAR(50),
	Message TEXT,
	`__inserted_on` DATETIME NOT NULL,
	`__timestamp` TIMESTAMP NOT NULL,
	PRIMARY KEY  (`__id`)
);